# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-04 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20181102_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('price', models.CharField(max_length=30)),
                ('unit', models.CharField(max_length=10)),
                ('headimg', models.CharField(max_length=120)),
                ('img1', models.CharField(max_length=120)),
                ('img2', models.CharField(max_length=120)),
                ('img3', models.CharField(max_length=120)),
                ('img4', models.CharField(max_length=120)),
                ('img5', models.CharField(max_length=120)),
                ('img6', models.CharField(max_length=120)),
                ('img7', models.CharField(max_length=120)),
                ('img13', models.CharField(max_length=120)),
                ('img19', models.CharField(max_length=120)),
                ('img20', models.CharField(max_length=120)),
                ('total', models.IntegerField()),
                ('potol', models.IntegerField()),
            ],
        ),
    ]
