# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-04 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_goods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='headimg',
            new_name='headImg',
        ),
    ]
