# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-04 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20181104_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='detail',
            field=models.CharField(default='', max_length=256),
        ),
    ]
